sonar.host.url=http://localhost:9000
sonar.projectKey=refactoring-ull
sonar.projectName=refactoring-ull
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml